### ISSUE TITLE
Find ffi.h outside of /usr/include

### ISSUE THREAD

**Issue by flwyd** [marcIhm/yabasic#41]
The [MacPorts](https://macports.org) distribution of `yabasic` fails in the configure step because `configure` can't find `libffi`.  MacPorts installs everything in `/opt/local` and `ffi.h` in particular is in `/opt/local/lib/libffi-3.2.1/include`.

I can get `yabasic` to install by configuring the `Portfile` to pass `--disable-use-ffi` to `configure`.  However, it would be nice if `configure` could locate the libffi installation and pass it as a `-I` parameter to the compiler.  Two standard ways to handle this:

1.   Accept a `--with-libffi=/path/to/ffi` argument to `configure`.  (Some packages have `--with-ffi-include` and `--with-ffi-lib` for separate `-I` and `-L` paths.)
2.   If [pkg-config](https://en.wikipedia.org/wiki/Pkg-config) is present, call `pkg-config --cflags libffi` and `pkg-config --libs libffi` and pass the results through to the `Makefile`.

**Comment by marcIhm** [comment]
Hi Trevor, 
thanx I will look into this !
Generally speaking, I am interested in a standard way to support yabasic on a Mac (without having a Mac myself ...). So your mail is very welcome and I will try to add those switches. Please stand by :-)
On 29.03.2020 06:17:31, Trevor Stone <notifications@github.com> wrote:
The MacPorts [https://macports.org] distribution of yabasic fails in the configure step because configure can't find libffi. MacPorts installs everything in /opt/local and ffi.h in particular is in /opt/local/lib/libffi-3.2.1/include.
I can get yabasic to install by configuring the Portfile to pass --disable-use-ffi to configure. However, it would be nice if configure could locate the libffi installation and pass it as a -I parameter to the compiler. Two standard ways to handle this:
* Accept a --with-libffi=/path/to/ffi argument to configure. (Some packages have --with-ffi-include and --with-ffi-lib for separate -I and -L paths.)
* If pkg-config [https://en.wikipedia.org/wiki/Pkg-config] is present, call pkg-config --cflags libffi and pkg-config --libs libffi and pass the results through to the Makefile.

**Comment by marcIhm** [comment]
Hi Trevor,
thanx for suggesting pkg-config !
Version 2.86.7 uses it and its configure now has a switch --with-ffi .
Could you please give it a try (tar-file attached) ?
regards
Marc

On 29.03.2020 06:17:31, Trevor Stone <notifications@github.com> wrote:
The MacPorts [https://macports.org] distribution of yabasic fails in the configure step because configure can't find libffi. MacPorts installs everything in /opt/local and ffi.h in particular is in /opt/local/lib/libffi-3.2.1/include.
I can get yabasic to install by configuring the Portfile to pass --disable-use-ffi to configure. However, it would be nice if configure could locate the libffi installation and pass it as a -I parameter to the compiler. Two standard ways to handle this:
* Accept a --with-libffi=/path/to/ffi argument to configure. (Some packages have --with-ffi-include and --with-ffi-lib for separate -I and -L paths.)
* If pkg-config [https://en.wikipedia.org/wiki/Pkg-config] is present, call pkg-config --cflags libffi and pkg-config --libs libffi and pass the results through to the Makefile.

**Comment by marcIhm** [comment]
If I understand Trevor correctly (private communication), this is fixed with a small mod he suggested and which I included in configure.ac.

**Comment by marcIhm** [comment]
yabasic 2.86.8 has another small change in this area, so I am leaving this open for another while ...

**Comment by marcIhm** [comment]
Okay hopefully.
