### ISSUE TITLE
Is there a way to change the font of the terminal ?

### ISSUE THREAD

**Issue by arrosev** [marcIhm/yabasic#61]
This is the best Basic I've found so far for printing strings in multiple languages. Can I change the font for the terminal ?

**Comment by marcIhm** [comment]
Hi, yabasic always uses the console of the operating system; under Windows this is the same console as it is used for cmd ... you might be able to change the font by right-clicking on the title bar (cannot check, because I am not near my computer for some days ...)regardsMarcVon meinem iPhone gesendetAm 18.03.2024 um 19:33 schrieb Arrose ***@***.***>:﻿
This is the best Basic I've found so far for printing strings in multiple languages. Can I change the font for the terminal ?

**Comment by arrosev** [comment]
Thank you for your reply.
